### ISSUE TITLE
Hardware

### ISSUE THREAD

**Issue by shocK0802** [uLipe/espFoC#1]
What series of hardware do I need when using this code to control a motor?
--ESP32
--DRV8301
Do I need some other components?

**Comment by uLipe** [comment]
Hello @shocK0802 , yes you just need an ESP32 board, an power stage compatible with 3-PWM output, DRV8301 offers that option. 

Also you need to attach an magnetic encoder to your motor, an AS5600 based board is required.

Soon I will be merging a wiring block diagram refer it from here: https://github.com/uLipe/espFoC/pull/2

Also you can port your custom encoder driver please have a look to the drivers folder.
